import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Language from '#models/language'
import { DateTime } from 'luxon'

export default class extends BaseSeeder {
  async run() {
    await Language.createMany([
      { name: 'Afrikaans' },
      { name: 'Albanian' },
      { name: 'Amharic' },
      { name: 'Arabic' },
      { name: 'Aramaic' },
      { name: 'Armenian' },
      { name: 'Aymara' },
      { name: 'Azerbaijani' },
      { name: 'Basque' },
      { name: 'Belarusian' },
      { name: 'Belizean Creole' },
      { name: 'Bengali' },
      { name: 'Berber' },
      { name: 'Bislama' },
      { name: 'Bosnian' },
      { name: 'Bulgarian' },
      { name: 'Burmese' },
      { name: 'Carolinian' },
      { name: 'Catalan' },
      { name: 'Chamorro' },
      { name: 'Chewa' },
      { name: 'Chibarwe' },
      { name: 'Chinese' },
      { name: 'Comorian' },
      { name: 'Cook Islands Māori' },
      { name: 'Croatian' },
      { name: 'Czech', createdAt: DateTime.now() },
      { name: 'Danish', createdAt: DateTime.now() },
      { name: 'Dari', createdAt: DateTime.now() },
      { name: 'Dutch', createdAt: DateTime.now() },
      { name: 'Dzongkha', createdAt: DateTime.now() },
      { name: 'English', createdAt: DateTime.now() },
      { name: 'Estonian', createdAt: DateTime.now() },
      { name: 'Faroese', createdAt: DateTime.now() },
      { name: 'Fiji Hindi', createdAt: DateTime.now() },
      { name: 'Fijian', createdAt: DateTime.now() },
      { name: 'Filipino', createdAt: DateTime.now() },
      { name: 'Finnish', createdAt: DateTime.now() },
      { name: 'French', createdAt: DateTime.now() },
      { name: 'Galician', createdAt: DateTime.now() },
      { name: 'Georgian', createdAt: DateTime.now() },
      { name: 'German', createdAt: DateTime.now() },
      { name: 'Gilbertese', createdAt: DateTime.now() },
      { name: 'Greek', createdAt: DateTime.now() },
      { name: 'Greenlandic', createdAt: DateTime.now() },
      { name: 'Guaraní', createdAt: DateTime.now() },
      { name: 'Guernésiais', createdAt: DateTime.now() },
      { name: 'Haitian Creole', createdAt: DateTime.now() },
      { name: 'Hassaniya', createdAt: DateTime.now() },
      { name: 'Hebrew', createdAt: DateTime.now() },
      { name: 'Herero', createdAt: DateTime.now() },
      { name: 'Hindi', createdAt: DateTime.now() },
      { name: 'Hiri Motu', createdAt: DateTime.now() },
      { name: 'Hungarian', createdAt: DateTime.now() },
      { name: 'Icelandic', createdAt: DateTime.now() },
      { name: 'Indonesian', createdAt: DateTime.now() },
      { name: 'Irish', createdAt: DateTime.now() },
      { name: 'Italian', createdAt: DateTime.now() },
      { name: 'Jamaican Patois', createdAt: DateTime.now() },
      { name: 'Japanese', createdAt: DateTime.now() },
      { name: 'Jèrriais', createdAt: DateTime.now() },
      { name: 'Kalanga', createdAt: DateTime.now() },
      { name: 'Kazakh', createdAt: DateTime.now() },
      { name: 'Khmer', createdAt: DateTime.now() },
      { name: 'Khoekhoe', createdAt: DateTime.now() },
      { name: 'Khoisan', createdAt: DateTime.now() },
      { name: 'Kikongo', createdAt: DateTime.now() },
      { name: 'Kinyarwanda', createdAt: DateTime.now() },
      { name: 'Kirundi', createdAt: DateTime.now() },
      { name: 'Korean', createdAt: DateTime.now() },
      { name: 'Kwangali', createdAt: DateTime.now() },
      { name: 'Kyrgyz', createdAt: DateTime.now() },
      { name: 'Lao', createdAt: DateTime.now() },
      { name: 'Latin', createdAt: DateTime.now() },
      { name: 'Latvian', createdAt: DateTime.now() },
      { name: 'Lingala', createdAt: DateTime.now() },
      { name: 'Lithuanian', createdAt: DateTime.now() },
      { name: 'Lozi', createdAt: DateTime.now() },
      { name: 'Luxembourgish', createdAt: DateTime.now() },
      { name: 'Macedonian', createdAt: DateTime.now() },
      { name: 'Malagasy', createdAt: DateTime.now() },
      { name: 'Malay', createdAt: DateTime.now() },
      { name: 'Maldivian', createdAt: DateTime.now() },
      { name: 'Maltese', createdAt: DateTime.now() },
      { name: 'Manx', createdAt: DateTime.now() },
      { name: 'Marshallese', createdAt: DateTime.now() },
      { name: 'Mauritian Creole', createdAt: DateTime.now() },
      { name: 'Mongolian', createdAt: DateTime.now() },
      { name: 'Montenegrin', createdAt: DateTime.now() },
      { name: 'Māori', createdAt: DateTime.now() },
      { name: 'Nauru', createdAt: DateTime.now() },
      { name: 'Ndau', createdAt: DateTime.now() },
      { name: 'Ndonga', createdAt: DateTime.now() },
      { name: 'Nepali', createdAt: DateTime.now() },
      { name: 'New Zealand Sign Language', createdAt: DateTime.now() },
      { name: 'Niuean', createdAt: DateTime.now() },
      { name: 'Norfuk', createdAt: DateTime.now() },
      { name: 'Northern Ndebele', createdAt: DateTime.now() },
      { name: 'Norwegian', createdAt: DateTime.now() },
      { name: 'Norwegian Bokmål', createdAt: DateTime.now() },
      { name: 'Norwegian Nynorsk', createdAt: DateTime.now() },
      { name: 'Palauan', createdAt: DateTime.now() },
      { name: 'Papiamento', createdAt: DateTime.now() },
      { name: 'Pashto', createdAt: DateTime.now() },
      { name: 'Persian (Farsi)', createdAt: DateTime.now() },
      { name: 'Polish', createdAt: DateTime.now() },
      { name: 'Portuguese', createdAt: DateTime.now() },
      { name: 'Quechua', createdAt: DateTime.now() },
      { name: 'Romanian', createdAt: DateTime.now() },
      { name: 'Romansh', createdAt: DateTime.now() },
      { name: 'Russian', createdAt: DateTime.now() },
      { name: 'Sami', createdAt: DateTime.now() },
      { name: 'Samoan', createdAt: DateTime.now() },
      { name: 'Sango', createdAt: DateTime.now() },
      { name: 'Serbian', createdAt: DateTime.now() },
      { name: 'Seychellois Creole', createdAt: DateTime.now() },
      { name: 'Shona', createdAt: DateTime.now() },
      { name: 'Sinhala', createdAt: DateTime.now() },
      { name: 'Slovak', createdAt: DateTime.now() },
      { name: 'Slovene', createdAt: DateTime.now() },
      { name: 'Somali', createdAt: DateTime.now() },
      { name: 'Sorani', createdAt: DateTime.now() },
      { name: 'Sotho', createdAt: DateTime.now() },
      { name: 'Southern Ndebele', createdAt: DateTime.now() },
      { name: 'Southern Sotho', createdAt: DateTime.now() },
      { name: 'Spanish', createdAt: DateTime.now() },
      { name: 'Swahili', createdAt: DateTime.now() },
      { name: 'Swazi', createdAt: DateTime.now() },
      { name: 'Swedish', createdAt: DateTime.now() },
      { name: 'Swiss German', createdAt: DateTime.now() },
      { name: 'Tajik', createdAt: DateTime.now() },
      { name: 'Tamil', createdAt: DateTime.now() },
      { name: 'Tetum', createdAt: DateTime.now() },
      { name: 'Thai', createdAt: DateTime.now() },
      { name: 'Tigrinya', createdAt: DateTime.now() },
      { name: 'Tok Pisin', createdAt: DateTime.now() },
      { name: 'Tokelauan', createdAt: DateTime.now() },
      { name: 'Tonga', createdAt: DateTime.now() },
      { name: 'Tongan', createdAt: DateTime.now() },
      { name: 'Tshiluba', createdAt: DateTime.now() },
      { name: 'Tsonga', createdAt: DateTime.now() },
      { name: 'Tswana', createdAt: DateTime.now() },
      { name: 'Turkish', createdAt: DateTime.now() },
      { name: 'Turkmen', createdAt: DateTime.now() },
      { name: 'Tuvaluan', createdAt: DateTime.now() },
      { name: 'Ukrainian', createdAt: DateTime.now() },
      { name: 'Upper Guinea Creole', createdAt: DateTime.now() },
      { name: 'Urdu', createdAt: DateTime.now() },
      { name: 'Uzbek', createdAt: DateTime.now() },
      { name: 'Venda', createdAt: DateTime.now() },
      { name: 'Vietnamese', createdAt: DateTime.now() },
      { name: 'Xhosa', createdAt: DateTime.now() },
      { name: 'Zimbabwean Sign Language', createdAt: DateTime.now() },
      { name: 'Zulu', createdAt: DateTime.now() },
    ])
  }
}
